### ISSUE TITLE
dockerimage tags 2.3.8-alpine-x does not provided on dockerhub

### ISSUE THREAD

**Issue by r-okui** [pgroonga/docker#12]
The only way to specify the version 2.8.8 tag on DockerHub is `latest-...`. 
Could you please provide the `2.3.8-...` tag?

**Comment by komainu8** [comment]
@r-okui Thank you for your report.
We provided the `2.3.8-...` tag. Could you check this?

**Comment by r-okui** [comment]
Thank you for your very quick response!
