### ISSUE TITLE
Add auto test mechanism

### ISSUE THREAD

**Issue by kou** [pgroonga/docker#15]
It's better that we use PGroonga's `pg_regress` based test suite.

**Comment by ZenLiuCN** [comment]
for in building time or for end users?
in case one maybe add just add github hook should do the trick.

**Comment by kou** [comment]
For end users.
I think that we can implement this by the followings:
1. Checkout corresponding PGroonga's repository ( https://github.com/pgroonga/pgroonga/tree/2.4.2 for PGroonga 2.4.2)
2. Run a built PGroonga's Docker image with volumed
3. Run `pg_regress` on host not in the running Docker image (We can use `pg_regress` on host because `pg_regress` can connect to PostgreSQL that is running on other machine.)

**Comment by ZenLiuCN** [comment]
So, if I am corretly got your Idea.
1. There are no need to modify the docker image build process.
2. It may offer as two way:
2.1  Offer as just a section of help document, E.g. `how to use 'pg_regress' to validate pgroona in docker`;
2.2  Offer a tool to do this;

in both options, I think that be a part of  `pgroona/pgroona.github.io` or `pgroona/pgroona`.

**Comment by kou** [comment]
Hmm. What did you mean "for in building time" and "for end users"?

I want to verify our built images before end users use them. It's for preventing end users getting an error.

**Comment by ZenLiuCN** [comment]
"for in building time" , I means in the stage "build and publish a Docker image". ^_^

**Comment by kou** [comment]
Thanks.
Then, "for in building time" is my answer.

**Comment by ZenLiuCN** [comment]
#18 already add some test purpose, maybe add those step:
1. checkout or download same version of pgroona source；
2. start a valid docker container for test;
3. attach the extracted source code folder and run a new docker container to execute `pg_regress`；（should be found at `usr\local\lib\postgresql\pgxs\src\test\regress\`）;

**Comment by ZenLiuCN** [comment]
a likely script fragment maybe:
```sh
curl --request GET -sL \
     --url 'https://github.com/pgroonga/pgroonga/releases/download/2.4.2/pgroonga-2.4.2.tar.gz'\
     --output 'src.tar.gz' && \
tar -C src -xzvf src.tar.gz && \
docker run \
  -v src:/tmp/tests/
  ${docker_image} \
  /usr/local/lib/postgresql/pgxs/src/test/regress/pg_regress  \
  --inputdir=tmp/tests/
  --schedule=/tmp/tests/some_schedule
```
I am not familiar with pg_regress, but this may worthy to have a try.

**Comment by kou** [comment]
We should use https://github.com/pgroonga/docker/blob/master/.github/workflows/build.yml instead of https://github.com/pgroonga/docker/blob/master/.github/workflows/test-docker-images.yml because the latter is for published images. If we use the latter, we can't detect test failure before we publish.

**Comment by ZenLiuCN** [comment]
in that case, some more references needs to be checked.
current all sources are only exists in a docker building env, and we may wanna those are accessable after build.
maybe two options exists:
1. change the docker file to do regress tests (may broken some files, not a best choice).
2. addtional stage after build image but before push image (checking on support [docker/build-push-action](https://github.com/docker/build-push-action) ).

**Comment by ZenLiuCN** [comment]
https://docs.docker.com/build/ci/github-actions/examples/#test-your-image-before-pushing-it
this maybe helpful

**Comment by kou** [comment]
Yes. I like the approach.

**Comment by ZenLiuCN** [comment]
here is a basic script, and I got some problem
1. seems that pgroonga use make to do the pg_regress thing, I cant figure out how to do it within a docker container.
   (if there are `any_schedule` like files exists, it will be done with `--schedule` parameter )
2. other things seems as work expected. 
```sh
# download sources
curl https://packages.groonga.org/source/pgroonga/pgroonga-2.4.2.tar.gz >> src.tar.gz && \
tar xf src.tar.gz && \
rm -rf src.tar.gz 
# start a server
docker run --name pg \
-d -ePOSTGRES_DB=regress \
-ePOSTGRES_PASSWORD=regress \
-ePOSTGRES_USER=regress \
-v ${pwd}/pgroonga-2.4.2:/tmp/tests \
groonga/pgroonga:2.4.2-alpine-15-slim
# start regress
docker exec pg /usr/local/lib/postgresql/pgxs/src/test/regress/pg_regress \
--inputdir=/tmp/tests \
--port=5432 \
--user=regress 
# shutdown server
docker stop pg && docker rm pg
```

**Comment by kou** [comment]
We can generate schedule file by `cd pgroonga-2.4.2/ && ruby test/prepare.rb > schedule`.

**Comment by ZenLiuCN** [comment]
that will have more extra components required，I wander that won't be easy with github hooks.

**Comment by kou** [comment]
We can use `ruby` in GitHub Actions by default.

**Comment by ZenLiuCN** [comment]
so，that worthy a try. github have been blocked by the state firewall again recently. may U got time to try that solution?

**Comment by kou** [comment]
Oh. OK. I'll do it later.

**Comment by kou** [comment]
Implemented.
