### ISSUE TITLE
https://github.com/pgroonga/docker/tree/3.0.2/debian/15/Dockerfile 404

### ISSUE THREAD

**Issue by leeyisoft** [pgroonga/docker#26]
https://github.com/pgroonga/docker/tree/3.0.2/debian/15/Dockerfile

**Comment by komainu8** [comment]
@leeyisoft 
Thanks!
I am releasing this version now.
However, this version may have problem. Therefore, we are stopping  provide this dockerfile now.

**Comment by leeyisoft** [comment]
I see. When will the next version of Dockerfile be released?

**Comment by leeyisoft** [comment]
By the way, can you and postgis jointly launch a Dockerfile including postgis and pgroonga (of course, both projects are excellent open source projects, I can refer to your own Dockerfile integration);

In my opinion, it would be better to have more technical professionals to maintain a "Postgre Stack" like "Redis Stack"

**Comment by leeyisoft** [comment]
I've just seen https://stackgres.io/ and it's a bit complicated

**Comment by kou** [comment]
You may want to use https://supabase.com/ .

**Comment by kou** [comment]
Newer version have been released.

More full-stack Docker image: We should work on it out of this repository if we need it. We can install PGroonga by `apt`/`dnf`. So installing PGroonga to a Docker image isn't hard.
