### ISSUE TITLE
PostgreSQL 16

### ISSUE THREAD

**Issue by CGSgeosite** [pgroonga/docker#34]
When will the Dockerfile for pg16 be released?

**Comment by komainu8** [comment]
@CGSgeosite 
Thank you for your report!

**Comment by CGSgeosite** [comment]
Thank you very much for your timely response and great contribution.

**Comment by CGSgeosite** [comment]
We intend to merge the PostGIS and pgroonga images, but we couldn't find a pgroonga-dockerfile based on postgres:16-bullseye. How can we resolve this issue?

**Comment by kou** [comment]
Why do you want to use bullseye not bookworm?

**Comment by CGSgeosite** [comment]
Because PostGIS does not provide a Dockerfile for Bookworm.

**Comment by kou** [comment]
Could you show a URL of PostGIS's Dockerfile?

**Comment by CGSgeosite** [comment]
https://github.com/postgis/docker-postgis/tree/master/16-master

**Comment by kou** [comment]
https://github.com/postgis/docker-postgis/blob/master/16-3.4/Dockerfile instead?
Do you want to use unreleased PostGIS?

**Comment by CGSgeosite** [comment]
No,

**Comment by kou** [comment]
I see. The following code will work for bullseye too: https://github.com/pgroonga/docker/blob/821fe9475867e954f541be955958b010393aa22a/debian/16/Dockerfile#L3-L21

**Comment by CGSgeosite** [comment]
32.83 Reading package lists...
33.31 Building dependency tree...
33.43 Reading state information...
33.56 E: Unable to locate package postgresql-16-pgdg-pgroonga

**Comment by CGSgeosite** [comment]
The above code cannot work in Bullseye. Please help me solve this, it's giving me trouble.

**Comment by kou** [comment]
Ah, we don't provide PGroonga deb for bullseye.

You can choose one of them:

* Use PGroonga's Docker image instead of PostGIS's Docker image as a base Docker image
* Ask PostGIS to add bookworm based Docker image
* Use PostgreSQL's bookworm Docker image as a Docker image and install PGroonga and PostGIS by yourself

**Comment by CGSgeosite** [comment]
Thank you for your patience and guidance.
