### ISSUE TITLE
Error when running Dockerfile for PGroonga

### ISSUE THREAD

**Issue by blueowlgreenfish** [pgroonga/docker#36]
I use Debian and use the exact Dockerfile provided by PGroonga as you can see [here](https://github.com/pgroonga/docker/blob/main/debian/16/Dockerfile).
It was working before, but it now generates error saying `Version '3.1.5-1' for 'postgresql-16-pgdg-pgroonga' was not found`.
Any idea?

**Comment by kou** [comment]
Could you show full log?

**Comment by blueowlgreenfish** [comment]
=> ERROR [database 2/2] RUN   apt update &&   apt install -y -V lsb-release wget &&   wget https://apache.jfrog.io/artifactory/arrow/debian/apache-arrow-apt-source-latest-bookworm.deb  28.7s
------
 > [database 2/2] RUN   apt update &&   apt install -y -V lsb-release wget &&   wget https://apache.jfrog.io/artifactory/arrow/debian/apache-arrow-apt-source-latest-bookworm.deb &&   apt install -y -V ./apache-arrow-apt-source-latest-bookworm.deb &&   rm apache-arrow-apt-source-latest-bookworm.deb &&   wget https://packages.groonga.org/debian/groonga-apt-source-latest-bookworm.deb &&   apt install -y -V ./groonga-apt-source-latest-bookworm.deb &&   rm groonga-apt-source-latest-bookworm.deb &&   apt update &&   apt install -y -V     postgresql-16-pgdg-pgroonga=3.1.5-1     groonga-normalizer-mysql     groonga-token-filter-stem     groonga-tokenizer-mecab &&   apt clean &&   rm -rf /var/lib/apt/lists/*:
0.260
0.260 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
0.260
0.474 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
0.991 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
1.071 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
1.167 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8,780 kB]
1.813 Get:5 http://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [123 kB]
3.156 Get:6 http://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [297 kB]
8.265 Get:7 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [6,408 B]
8.299 Get:8 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [96.2 kB]
9.575 Fetched 9,554 kB in 9s (1,028 kB/s)
9.575 Reading package lists...
10.47 Building dependency tree...
10.63 Reading state information...
10.64 All packages are up to date.
10.65
10.65 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
10.65
10.66 Reading package lists...
11.33 Building dependency tree...
11.50 Reading state information...
11.69 The following additional packages will be installed:
11.69    ca-certificates (20230311)
11.69    libpsl5 (0.21.2-1)
11.69    publicsuffix (20230209.2326-1)
11.77 The following NEW packages will be installed:
11.77    ca-certificates (20230311)
11.77    libpsl5 (0.21.2-1)
11.77    lsb-release (12.0-1)
11.77    publicsuffix (20230209.2326-1)
11.77    wget (1.21.3-1+b2)
11.91 0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
11.91 Need to get 1,329 kB of archives.
11.91 After this operation, 4,548 kB of additional disk space will be used.
11.91 Get:1 http://deb.debian.org/debian bookworm/main amd64 ca-certificates all 20230311 [153 kB]
12.01 Get:2 http://deb.debian.org/debian bookworm/main amd64 libpsl5 amd64 0.21.2-1 [58.7 kB]
12.02 Get:3 http://deb.debian.org/debian bookworm/main amd64 wget amd64 1.21.3-1+b2 [984 kB]
12.41 Get:4 http://deb.debian.org/debian bookworm/main amd64 lsb-release all 12.0-1 [6,416 B]
12.41 Get:5 http://deb.debian.org/debian bookworm/main amd64 publicsuffix all 20230209.2326-1 [126 kB]
12.55 debconf: delaying package configuration, since apt-utils is not installed
12.58 Fetched 1,329 kB in 1s (2,108 kB/s)
12.61 Selecting previously unselected package ca-certificates.
(Reading database ... 12085 files and directories currently installed.)
12.62 Preparing to unpack .../ca-certificates_20230311_all.deb ...
12.63 Unpacking ca-certificates (20230311) ...
12.68 Selecting previously unselected package libpsl5:amd64.
12.68 Preparing to unpack .../libpsl5_0.21.2-1_amd64.deb ...
12.69 Unpacking libpsl5:amd64 (0.21.2-1) ...
12.73 Selecting previously unselected package wget.
12.73 Preparing to unpack .../wget_1.21.3-1+b2_amd64.deb ...
12.73 Unpacking wget (1.21.3-1+b2) ...
12.88 Selecting previously unselected package lsb-release.
12.88 Preparing to unpack .../lsb-release_12.0-1_all.deb ...
12.89 Unpacking lsb-release (12.0-1) ...
12.91 Selecting previously unselected package publicsuffix.
12.91 Preparing to unpack .../publicsuffix_20230209.2326-1_all.deb ...
12.92 Unpacking publicsuffix (20230209.2326-1) ...
12.96 Setting up libpsl5:amd64 (0.21.2-1) ...
12.97 Setting up wget (1.21.3-1+b2) ...
12.97 Setting up ca-certificates (20230311) ...
13.07 debconf: unable to initialize frontend: Dialog
13.07 debconf: (TERM is not set, so the dialog frontend is not usable.)
13.07 debconf: falling back to frontend: Readline
13.08 debconf: unable to initialize frontend: Readline
13.08 debconf: (This frontend requires a controlling tty.)
13.08 debconf: falling back to frontend: Teletype
13.83 Updating certificates in /etc/ssl/certs...
14.91 140 added, 0 removed; done.
14.94 Setting up lsb-release (12.0-1) ...
14.95 Setting up publicsuffix (20230209.2326-1) ...
14.96 Processing triggers for libc-bin (2.36-9+deb12u3) ...
14.97 Processing triggers for ca-certificates (20230311) ...
14.98 Updating certificates in /etc/ssl/certs...
16.00 0 added, 0 removed; done.
16.00 Running hooks in /etc/ca-certificates/update.d...
16.00 done.
16.04 --2023-11-05 00:00:46--  https://apache.jfrog.io/artifactory/arrow/debian/apache-arrow-apt-source-latest-bookworm.deb
16.06 Resolving apache.jfrog.io (apache.jfrog.io)... 44.226.59.123, 100.21.156.46, 54.185.186.5
16.27 Connecting to apache.jfrog.io (apache.jfrog.io)|44.226.59.123|:443... connected.
17.17 HTTP request sent, awaiting response... 200
17.58 Length: 63068 (62K) [application/x-debian-package]
17.58 Saving to: ‘apache-arrow-apt-source-latest-bookworm.deb’
17.58
17.58      0K .......... .......... .......... .......... .......... 81% 81.3K 0s
18.19     50K .......... .                                          100% 36.2M=0.6s
18.20
18.20 2023-11-05 00:00:48 (100 KB/s) - ‘apache-arrow-apt-source-latest-bookworm.deb’ saved [63068/63068]
18.20
18.20
18.20 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
18.20
18.21 Reading package lists...
18.87 Building dependency tree...
19.02 Reading state information...
19.23 The following NEW packages will be installed:
19.23    apache-arrow-apt-source (14.0.0-1)
19.25 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
19.25 Need to get 0 B/63.1 kB of archives.
19.25 After this operation, 80.9 kB of additional disk space will be used.
19.25 Get:1 /apache-arrow-apt-source-latest-bookworm.deb apache-arrow-apt-source all 14.0.0-1 [63.1 kB]
19.38 debconf: delaying package configuration, since apt-utils is not installed
19.43 Selecting previously unselected package apache-arrow-apt-source.
(Reading database ... 12365 files and directories currently installed.)
19.44 Preparing to unpack .../apache-arrow-apt-source-latest-bookworm.deb ...
19.44 Unpacking apache-arrow-apt-source (14.0.0-1) ...
19.48 Setting up apache-arrow-apt-source (14.0.0-1) ...
19.51 --2023-11-05 00:00:49--  https://packages.groonga.org/debian/groonga-apt-source-latest-bookworm.deb
19.53 Resolving packages.groonga.org (packages.groonga.org)... 153.126.209.250, 2401:2500:102:3040:153:126:209:250
19.93 Connecting to packages.groonga.org (packages.groonga.org)|153.126.209.250|:443... connected.
20.10 HTTP request sent, awaiting response... 200 OK
20.17 Length: 7864 (7.7K) [application/vnd.debian.binary-package]
20.17 Saving to: ‘groonga-apt-source-latest-bookworm.deb’
20.17
20.17      0K .......                                               100%  110M=0s
20.17
20.17 2023-11-05 00:00:50 (110 MB/s) - ‘groonga-apt-source-latest-bookworm.deb’ saved [7864/7864]
20.17
20.18
20.18 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
20.18
20.19 Reading package lists...
20.84 Building dependency tree...
21.00 Reading state information...
21.24 The following NEW packages will be installed:
21.24    groonga-apt-source (2023.2.2-1)
21.26 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
21.26 Need to get 0 B/7,864 B of archives.
21.26 After this operation, 24.6 kB of additional disk space will be used.
21.26 Get:1 /groonga-apt-source-latest-bookworm.deb groonga-apt-source all 2023.2.2-1 [7,864 B]
21.39 debconf: delaying package configuration, since apt-utils is not installed
21.44 Selecting previously unselected package groonga-apt-source.
(Reading database ... 12370 files and directories currently installed.)
21.45 Preparing to unpack .../groonga-apt-source-latest-bookworm.deb ...
21.46 Unpacking groonga-apt-source (2023.2.2-1) ...
21.49 Setting up groonga-apt-source (2023.2.2-1) ...
21.52
21.52 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
21.52
21.67 Hit:1 http://deb.debian.org/debian bookworm InRelease
21.69 Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
21.72 Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
22.10 Hit:4 http://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease
22.38 Get:5 https://packages.groonga.org/debian bookworm InRelease [9,543 B]
22.53 Get:6 https://packages.groonga.org/debian bookworm/main Sources [16.9 kB]
22.59 Get:7 https://packages.groonga.org/debian bookworm/main amd64 Packages [39.7 kB]
23.11 Get:8 https://apache.jfrog.io/artifactory/arrow/debian bookworm InRelease [7,297 B]
23.80 Get:9 https://apache.jfrog.io/artifactory/arrow/debian bookworm/main Sources [19.1 kB]
24.67 Get:10 https://apache.jfrog.io/artifactory/arrow/debian bookworm/main amd64 Packages [161 kB]
25.62 Fetched 254 kB in 4s (62.5 kB/s)
25.62 Reading package lists...
26.93 Building dependency tree...
27.15 Reading state information...
27.17 All packages are up to date.
27.19
27.19 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
27.19
27.19 Reading package lists...
28.45 Building dependency tree...
28.71 Reading state information...
28.72 Package postgresql-16-pgdg-pgroonga is not available, but is referred to by another package.
28.72 This may mean that the package is missing, has been obsoleted, or
28.72 is only available from another source
28.72
28.73 E: Version '3.1.5-1' for 'postgresql-16-pgdg-pgroonga' was not found
------
failed to solve: process "/bin/sh -c apt update &&   apt install -y -V lsb-release wget &&   wget https://apache.jfrog.io/artifactory/arrow/debian/apache-arrow-apt-source-latest-bookworm.deb &&   apt install -y -V ./apache-arrow-apt-source-latest-bookworm.deb &&   rm apache-arrow-apt-source-latest-bookworm.deb &&   wget https://packages.groonga.org/debian/groonga-apt-source-latest-bookworm.deb &&   apt install -y -V ./groonga-apt-source-latest-bookworm.deb &&   rm groonga-apt-source-latest-bookworm.deb &&   apt update &&   apt install -y -V     postgresql-${POSTGRESQL_VERSION}-pgdg-pgroonga=${PGROONGA_VERSION}     groonga-normalizer-mysql     groonga-token-filter-stem     groonga-tokenizer-mecab &&   apt clean &&   rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by kou** [comment]
Thanks.
It seems that our APT repository's metadata is broken. I've fixed it. Could you try again?

**Comment by blueowlgreenfish** [comment]
It's working now.
Thanks!

**Comment by blueowlgreenfish** [comment]
It happened again today.
I guess it's not fully fixed?

**Comment by komainu8** [comment]
@blueowlgreenfish 
I've fixed our APT repository's metadata. Could you try again?

**Comment by blueowlgreenfish** [comment]
Yes, it works.
Thanks!

**Comment by blueowlgreenfish** [comment]
Did metadata break again?

**Comment by komainu8** [comment]
@blueowlgreenfish I've fixed it. Could you try again?
