### ISSUE TITLE
pgroonga not installed after building from Dockerfile

### ISSUE THREAD

**Issue by blueowlgreenfish** [pgroonga/docker#38]
I tried both debian and alpine images and both proceeded without errors.
However, when I enter psql and type `\dx`, pgroonga is not installed.

**Comment by kou** [comment]
You need to execute `CREATE EXTENSION pgroonga`.

**Comment by blueowlgreenfish** [comment]
It returns error `ERROR:  could not load library "/usr/lib/postgresql/16/lib/pgroonga.so": libarrow.so.1600: cannot open shared object file: No such file or directory`

**Comment by kou** [comment]
Ah, it's caused by https://github.com/apache/arrow/issues/41679 .
We can avoid this by rebuilding Groonga packages or using `libarrow1600=16.0.0-1` explicitly in our `Dockerfile`.

**Comment by kou** [comment]
Could you use a bit old images or Alpine based images for now?

**Comment by kou** [comment]
I think that it works now.
