### ISSUE TITLE
Support for Postgres 12

### ISSUE THREAD

**Issue by samijnih** [pgroonga/docker#4]
👋 

I love your lib and I use it for my functional / integration tests.

So I wanted to know if a postgres 12 could be setup? (with no trouble)

Sami

**Comment by kou** [comment]
`2.2.2-alphine-12` and `2.2.2-alphine-12-slim` images are building on Docker Hub. You can see the status at https://hub.docker.com/r/groonga/pgroonga/builds .

BTW, we are collecting PGroonga user list :-)
https://pgroonga.github.io/users/

**Comment by samijnih** [comment]
> `2.2.2-alphine-12` and `2.2.2-alphine-12-slim` images are building on Docker Hub. You can see the status at https://hub.docker.com/r/groonga/pgroonga/builds .
> 
> BTW, we are collecting PGroonga user list :-)
> https://pgroonga.github.io/users/

Will do for sure when my app will be live! thanks a lot!

**Comment by kou** [comment]
Oh. I've fixed.
