### ISSUE TITLE
Remove separate MeCab build step with CMake based build system

### ISSUE THREAD

**Issue by otegami** [pgroonga/docker#51]
ref: https://github.com/pgroonga/docker/issues/40

Now, Groonga can build [MeCab](https://taku910.github.io/mecab/) together with CMake.
So we can remove its build step from [alpine/build.sh](https://github.com/pgroonga/docker/blob/main/alpine/build.sh)

ref: https://github.com/groonga/groonga/blob/e5ecc368e7825621374d7b0c7662fa455ebd8dd3/CMakeLists.txt#L764-L769
ref: https://github.com/groonga/groonga/tree/main/vendor/mecab

**Comment by otegami** [comment]
https://github.com/pgroonga/docker/pull/48 のレビュー対応から進めていく。

**Comment by otegami** [comment]
```console
b60fd22098f3:/# ruby -v
bash: ruby: command not found
```

**Comment by otegami** [comment]
Ruby を入れてあげる。
```console
# apk add ruby
```

**Comment by otegami** [comment]
```console
b60fd22098f3:/# cd build/groonga-14.0.4/vendor/
/build/groonga-14.0.4/vendor# ruby download_mecab.rb
download_mecab.rb:62:in `spawn': No such file or directory - patch (Errno::ENOENT)
	from download_mecab.rb:62:in `block (4 levels) in download'
	from download_mecab.rb:61:in `pipe'
	from download_mecab.rb:61:in `block (3 levels) in download'
	from download_mecab.rb:60:in `chdir'
	from download_mecab.rb:60:in `block (2 levels) in download'
	from /usr/lib/ruby/3.3.0/open-uri.rb:162:in `open_uri'
	from /usr/lib/ruby/3.3.0/open-uri.rb:750:in `open'
	from download_mecab.rb:59:in `block in download'
	from download_mecab.rb:57:in `each'
	from download_mecab.rb:57:in `download'
	from download_mecab.rb:73:in `<main>'
b60fd22098f3:/build/groonga-14.0.4/vendor# cat download_mecab.rb
```

**Comment by otegami** [comment]
patch コマンドがなさそう。
下記を試すところから、次再開する。
```console
# apk add patch
```

**Comment by otegami** [comment]
問題なくうまく行った。
```console
/build/groonga-14.0.4/vendor# ruby download_mecab.rb
patching file src/dictionary.cpp
```

**Comment by otegami** [comment]
次にダウンロードしてビルドが通るところまで確認する。

**Comment by otegami** [comment]
> 次にダウンロードしてビルドが通るところまで確認する。

ここまで確認できた。
- https://github.com/pgroonga/docker/pull/48/files

```console
/build/groonga-14.0.4# psql -U pgroonga
psql (12.19)
Type "help" for help.

pgroonga=# CREATE TABLE memos (
pgroonga(#   id integer,
pgroonga(#   content text
pgroonga(# );
CREATE TABLE
pgroonga=# CREATE EXTENSION IF NOT EXISTS pgroonga;
CREATE EXTENSION
pgroonga=# CREATE INDEX pgroonga_content_index
pgroonga-#           ON memos
pgroonga-#        USING pgroonga (content)
pgroonga-#         WITH (tokenizer='TokenMecab');
CREATE INDEX
```

**Comment by otegami** [comment]
一気に変更を入れると差分が多いから下記の２つに分けて PR を出していこう。
- `download_mecab` をインストールするのに必要な `ruby` と `patch` を導入する PR
- `build.sh` で `download_mecab` 経由でインストールする対応をどうにゅうする PR

**Comment by kou** [comment]
いやぁ、これは一緒じゃないかなぁ。
わけるならまずは`alpine/16/`だけ`doewnload_mecab.rb`で、他の`alpine/*/`はそのまま、とかじゃないかな。でも、そのアプローチでレビューしやすいPRにするのはまだむずかしいんじゃないかな。

**Comment by otegami** [comment]
了解です。
そしたら今回は少しボリュームが増えてしまいますが、分けずにそのまま行こうと思います。

**Comment by otegami** [comment]
> わけるならまずはalpine/16/だけdoewnload_mecab.rbで、他のalpine/*/はそのまま、とかじゃないかな。

`build.sh` にて、OS バージョンで分岐する or 別のファイルを呼んで呼び出すくらいしか思いついていないのですが、
今度お時間のあるときにこんなパターンが良いんじゃないみたいなのあったら教えてくださいmm

**Comment by kou** [comment]
私なら別のファイルでやってみるかな。

**Comment by otegami** [comment]
ちょっと次回チャレンジしてみます！
