### ISSUE TITLE
pgroonga has a package for mysql

### ISSUE THREAD

**Issue by paichi81** [pgroonga/docker#6]
Is this necessary?

https://github.com/pgroonga/docker/blob/95496f279f55adacc7b69735290a520c34d20629/debian/12/Dockerfile#L12

**Comment by komainu8** [comment]
Yes. This is necessary.

Because groonga-normalizer-mysql is a kind of normalizer.
We can use the normalizer equivalent of utf8mb4_general_ci and utf8mb4_unicode_ci on PGroonga by using this as below.

```
CREATE TABLE memos (
  id integer,
  tag text
);

CREATE INDEX pgroonga_tag_index
          ON memos
       USING pgroonga (tag)
        WITH (plugins='normalizers/mysql', normalizer='NormalizerMySQLGeneralCI');
```

or

```
CREATE TABLE memos (
  id integer,
  tag text
);

CREATE INDEX pgroonga_tag_index
          ON memos
       USING pgroonga (tag)
        WITH (plugins='normalizers/mysql', normalizer='NormalizerMySQLUnicodeCI');
```
